
// constant for product reducer 
export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

// constant for product details reducer 
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

// a new product constant 
export const NEW_PRODUCT__REQUEST = "NEW_PRODUCT__REQUEST";
export const NEW_PRODUCT__SUCCESS = "NEW_PRODUCT__SUCCESS";
export const NEW_PRODUCT_RESET="NEW_PRODUCT_RESET";
export const NEW_PRODUCT__FAIL = "NEW_PRODUCT__FAIL";

// products constants for admin 
export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

// constant for review
export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

// delete product
export const DELETE_PRODUCT_REQUEST="DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_RESET="DELETE_PRODUCT_RESET";
export const DELETE_PRODUCT_FAIL="DELETE_PRODUCT_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";